// webapp-svelte/src/pages/auth/Login.svelte
<script lang="ts">
  import { login } from "@/api";
  import { Button, FormGroup, Label } from "@/modules/cdk";
  import { handleError } from "@/utils";
  
  let email = "";
  let password = "";

  function handleLogin() {
    login(email, password).catch(handleError);
  }
</script>

<form on:submit|preventDefault={handleLogin}>
  <FormGroup>
    <Label for="email">Email</Label>
    <input
      bind:value={email}
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Email address"
      required
    />
  </FormGroup>
  <FormGroup>
    <Label for="password">Password</Label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Password"
      bind:value={password}
      required
    />
    <div class="text-right mt-1">
      <router-link to="/forgotten-password"><small>Forgotten password ?</small></router-link>
    </div>
  </FormGroup>
  <Button type="submit" color="primary" class="pull-right">Login</Button>
</form>

<hr />

<p>Need an account ? <router-link to="/signup">Register</router-link></p>

// apps/admin/src/pages/login.vue
<script setup lang="ts">
import { post } from "~/api/rest";
import { handleError } from "~/utils";
import VTextField from "~cdk/VTextField.vue";
import VBtn from "~cdk/VBtn.vue";
import { useUserStore } from "~/store/user";

const user = useUserStore();
const route = useRoute();
const router = useRouter();

const form = reactive({
  email: "",
  password: "",
});

function leave() {
  if (route.query.redirect) {
    router.push(route.query.redirect as string);
  } else {
    router.push("/");
  }
}

async function login() {
  try {
    const data = await post("/account/login", { email: form.email, password: form.password });
    user.updateAuth(data);
  } catch (err) {
    handleError(err);
  }
}

whenever(() => !!user.user, leave, { immediate: true });
</script>

<template>
  <form @submit.prevent="login">
    <v-text-field v-model="form.email" label="Email" required type="email" class="my-2" />
    <v-text-field v-model="form.password" label="Password" required type="password" class="my-2" />
    <v-btn type="submit" class="my-1 float-right"> Log in </v-btn>
  </form>
</template>

<route lang="yaml">
name: login
meta:
  requiresAuth: false
</route>
