// webapp-vue/src/components/UserElo.vue
<template>
  <div border-variant="secondary" v-if="gamePreferences.some((pref) => pref.elo)">
    <h3 class="card-title">Elo</h3>
    <ul class="list-group text-left">
      <div
        v-for="gamePref in gamePreferences.filter((pref) => pref.elo)"
        :key="gamePref.game"
        :class="['list-group-item', 'list-group-item-action', 'py2']"
      >
        <span
          >{{ gameName(gamePref.game) }} - <b>{{ gamePref.elo.value }}</b> in
          {{ gamePref.elo.games | pluralize("game") }}</span
        >
      </div>
    </ul>
    <!-- <div class="py-1"/>
      <router-link :to="`/page/elo`">How it works</router-link> -->
  </div>
</template>
<script lang="ts">
import { Vue, Component, Prop, Watch } from "vue-property-decorator";
import { handleError } from "@/utils";
import { GamePreferences } from "@lib/gamepreferences";

@Component({
  async created(this: UserElo) {
    try {
      this.gamePreferences = await this.$axios.get(`/user/${this.userId}/games/elo`).then((r) => r.data);
    } catch (err) {
      handleError(err);
    } finally {
      this.loading = false;
    }
  },
  components: {},
})
export default class UserElo extends Vue {
  @Prop()
  userId: string;

  loading = true;

  gamePreferences: GamePreferences[] = [];

  gameName(game: string) {
    const info = this.$gameInfo.info(game, "latest");

    if (!info) {
      this.$gameInfo.loadGameInfo(game, "latest");
      return game;
    }

    return info.label;
  }
}
</script>

// webapp-svelte/src/components/User/UserElo.svelte
<script lang="ts">
import { boardgameInfo, get, loadBoardgame } from "@/api";
import { handleError, pluralize } from "@/utils";

import type { GamePreferences } from "@lib/gamepreferences";
import { Icon } from "@cdk";

export let userId: string;

let gamePreferences: GamePreferences[] = [];

const onUserIdChanged = () => get<GamePreferences[]>(`/user/${userId}/games/elo`).then(prefs => gamePreferences = prefs).catch(handleError)

$: onUserIdChanged(), [userId]

async function gameName(game: string): Promise<string> {
  const info = boardgameInfo(game, "latest");

  if (!info) {
    return loadBoardgame(game, "latest").then(() => gameName(game), err => {handleError(err); return "error"});
  }

  return info.label;
}

</script>

{#if gamePreferences.some((pref) => pref.elo)}
  <div>
    <h3 class="card-title">
      Elo <a href="/page/elo"><Icon name="info-circle-fill" class="text-secondary small" /></a>
    </h3>
    <ul class="list-group text-left">
      {#each gamePreferences.filter((pref) => !!pref.elo) as gamePref}
        <div class="list-group-item list-group-item-action py-2">
          <span>
            {#await gameName(gamePref.game) then name}
              {name} - <b>{gamePref.elo.value}</b> in
              {pluralize(gamePref.elo.games, "game")}
            {/await}
          </span>
        </div>
      {/each}
    </ul>
  </div>
{/if}
