// apps/web/src/components/Layout/Footer.svelte
<script lang="ts">
	import { resolve } from "$app/paths";
</script>

<footer
	class="mt-6 flex min-h-[60px] w-full items-center border-t border-gray-200 bg-gray-100 px-4 py-4 dark:border-gray-700 dark:bg-gray-900"
>
	<div class="mx-auto flex flex-row flex-wrap gap-4 text-sm">
		<a href="https://forum.boardgamers.space" class="text-gray-500 underline hover:text-primary dark:text-gray-400"
			>Forum</a
		>
		<a href="mailto:contact@boardgamers.space" class="text-gray-500 underline hover:text-primary dark:text-gray-400"
			>Contact</a
		>
		<a
			data-sveltekit-preload-data="hover"
			href={resolve("/(app)/page/[part1]", { part1: "source" })}
			class="text-gray-500 underline hover:text-primary dark:text-gray-400">Source</a
		>
		<a
			data-sveltekit-preload-data="hover"
			href={resolve("/(app)/page/[part1]", { part1: "privacy-policy" })}
			class="text-gray-500 underline hover:text-primary dark:text-gray-400">Privacy policy</a
		>
		<a
			data-sveltekit-preload-data="hover"
			href={resolve("/(app)/page/[part1]", { part1: "credits" })}
			class="text-gray-500 underline hover:text-primary dark:text-gray-400">Credits</a
		>
	</div>
</footer>

// apps/web/.fast-check/tsx/src/components/Layout/Footer.svelte.tsx
///<reference types="svelte" />
;function $$render() {
async () => { { svelteHTML.createElement("footer", { "class":`footer`,});
   { svelteHTML.createElement("div", { "class":`container`,});
     { svelteHTML.createElement("div", { "class":`row`,});
       { svelteHTML.createElement("div", { "class":`col-auto`,});
         { svelteHTML.createElement("a", {   "href":`https://forum.boardgamers.space`,"class":`text-muted`,});  }
       }
       { svelteHTML.createElement("div", { "class":`col-auto`,});
         { svelteHTML.createElement("a", {   "href":`mailto:contact@boardgamers.space`,"class":`text-muted`,});  }
       }
       { svelteHTML.createElement("div", { "class":`col-auto`,});
         { svelteHTML.createElement("a", {     "data-sveltekit-preload-data":`hover`,"href":`/page/source`,"class":`text-muted`,});  }
       }
       { svelteHTML.createElement("div", { "class":`col-auto`,});
         { svelteHTML.createElement("a", {     "data-sveltekit-preload-data":`hover`,"href":`/page/privacy-policy`,"class":`text-muted`,});  }
       }
       { svelteHTML.createElement("div", { "class":`col-auto`,});
         { svelteHTML.createElement("a", {     "data-sveltekit-preload-data":`hover`,"href":`/page/credits`,"class":`text-muted`,});  }
       }
     }
   }
 }


};
return { props: /** @type {Record<string, never>} */ ({}), exports: {}, bindings: "", slots: {}, events: {} }}
const Footer__SvelteComponent_ = __sveltets_2_isomorphic_component(__sveltets_2_partial(__sveltets_2_with_any_event($$render())));
/*Ωignore_startΩ*/type Footer__SvelteComponent_ = InstanceType<typeof Footer__SvelteComponent_>;
/*Ωignore_endΩ*/export default Footer__SvelteComponent_;
