// packages/web/webapp-svelte/src/components/Game/GameSidebar.svelte
<script lang="ts">
import { keyBy } from "lodash";
import { timerTime, oneLineMarked, handleError, confirm, duration, shortDuration } from "@/utils";
import type { PlayerInfo } from "@lib/game";
import Portal from "svelte-portal";
import { addActiveGame, playerStatus, removeActiveGame, user } from "@/store";
import { Button, Icon, Badge } from "@/modules/cdk";
import { post } from "@/api";
import { getContext, onDestroy } from "svelte";
import {GameLog, ReplayControls, GameNotes, GamePreferences, GameSettings} from './GameSidebar';
import type { GameContext } from "@/pages/Game.svelte";
import PlayerGameAvatar from "./components/PlayerGameAvatar.svelte";

const {game, players, gameInfo}: GameContext = getContext("game")

let secondsCounter = 0;

const interval = setInterval(() => {
  if (!document.hidden) {
    secondsCounter += 1;
  }
}, 1000);
onDestroy(() => clearInterval(interval))

let  requestedDrop: Record<string, boolean> = {};

$: userId = $user?._id
$: playerUser = $game?.players.find((pl) => pl._id === userId)
$: gameId = $game?._id

function status(playerId: string) {
  return $playerStatus?.find(pl => pl._id === playerId)?.status ?? 'offline'
}

function playerElo(playerId: string) {
  return $players.find((pl) => pl._id === playerId)?.elo ?? 0;
}

$: alwaysActive = $game?.options.timing.timer?.start === $game?.options.timing.timer?.end

$: currentPlayersById = keyBy($game?.currentPlayers ?? [], "_id");

function isCurrentPlayer(id: string) {
  return $game?.status !== "ended" && !!currentPlayersById[id];
}

const onGameChanged = () => {
  if (userId) {
    if (isCurrentPlayer(userId)) {
      addActiveGame(gameId)
    } else {
      removeActiveGame(gameId)
    }
  }
}

$: onGameChanged(), [userId, $game]

let remainingTimes: Record<string, number> = {}

function updateRemainingTimes() {
  const ret: Record<string, number> = {}
  for (const player of $game.players) {
    ret[player._id] = remainingTime(player)
  }

  remainingTimes = ret
}

$: updateRemainingTimes(), [secondsCounter]

function remainingTime(player: PlayerInfo) {
  const currentPlayer = currentPlayersById[player._id];
  if (currentPlayer) {
    // Trick to update every second
    return Math.floor((new Date(currentPlayer.deadline).getTime() - Date.now() + (secondsCounter % 1)) / 1000);
  }
  return Math.max(player.remainingTime, 0);
}

async function voteCancel() {
  if (await confirm("This vote cannot be taken back. If all active players vote to cancel, the game will be cancelled.")) {
    await post(`/game/${gameId}/cancel`).catch(handleError);
  }
}

async function quit() {
  await post(`/game/${gameId}/quit`).catch(handleError);
}

async function requestDrop(playerId: string) {
  await post(`/game/${gameId}/drop/${playerId}`)
    .then(() => (requestedDrop = {...requestedDrop, [playerId]: true}), handleError);
}

</script>

<Portal target="#sidebar">
  <h3 class="mt-75">Players</h3>
  {#each $game.players as player}
    <div class={"mb-1 d-flex align-items-center player-row"} class:active={isCurrentPlayer(player._id)}>
      <PlayerGameAvatar {userId} {player} status={status(player._id)} class="mr-2" />

      <div>
        <a href={`/user/${player.name}`} class="player-name" class:dropped={player.dropped}>
          {player.name}
        </a>
        <sup class="ml-1">
          {#if player.elo}
            {player.elo.initial} {player.elo.delta >= 0 ? "+" : "-"} {Math.abs(player.elo.delta)} elo
          {:else}
            {playerElo(player._id)} elo
          {/if}
        </sup>
        {#if $game.status === "active"}
          <span class="ml-1"> - {shortDuration(remainingTimes[player._id])}</span>
        {/if}
      </div>
    </div>
  {/each}
  <div class="mt-75">
    <Icon name="clock-history" class="mr-1" />
    {alwaysActive
      ? "24h"
      : `${timerTime($game.options.timing.timer.start)}-${timerTime($game.options.timing.timer.end)}`}
    / {duration($game.options.timing.timePerGame)} + {duration($game.options.timing.timePerMove)}
  </div>
  {#if $game.status === "ended"}
    <div class="mt-75">
      <b> Game ended! </b>
    </div>
  {/if}
  {#key $game.currentPlayers}
    {#if $user && isCurrentPlayer($user._id)}
      <div class="mt-75">
        <b class="your-turn">Your turn!</b>
      </div>
    {/if}
  {/key}
  {#if playerUser && $game.status !== "ended"}
    <div class="mt-75">
      <Button
        color="warning"
        size="sm"
        disabled={playerUser.dropped || playerUser.voteCancel || playerUser.quit}
        on:click={voteCancel}
      >
        Vote to cancel
      </Button>
      {#if $game.players.some((pl) => !!pl.dropped)}
        <Button size="sm" class="ml-2" disabled={playerUser.dropped || playerUser.quit} on:click={quit}>Quit</Button>
      {/if}
      {#each $game.players as player}
        {#if remainingTime(player) <= 0 && isCurrentPlayer(player._id) && !player.dropped && !player.quit}
          <Button
            size="sm"
            class="ml-2"
            color="danger"
            disabled={requestedDrop[player._id]}
            on:click={() => requestDrop(player._id)}
          >
            Drop {player.name}
          </Button>
        {/if}
      {/each}
    </div>
  {/if}

  <GameSettings />

  <GamePreferences />

  <GameNotes {gameId} />

  {#if $gameInfo.expansions?.length > 0}
    <div class="mt-75">
      <h3>Expansions</h3>
      {#each $game.game.expansions as expansion}
        <Badge color="info" class="mr-1">
          {$gameInfo.expansions.find((xp) => xp.name === expansion)?.label}
        </Badge>
      {/each}
    </div>
  {/if}

  <GameLog />

  <ReplayControls />

  {#if $gameInfo.options.some((x) => !!$game.game.options?.[x.name])}
    <div class="mt-75">
      <h3>Setup options</h3>
      {#each $gameInfo.options.filter((x) => !!$game.game.options[x.name]) as pref}
        <Badge color="secondary" class="mr-1">
          {#if pref.type === "checkbox"}
            {@html oneLineMarked(pref.label)}
          {:else if pref.type === "select" && pref.items && pref.items.some((x) => x.name === $game.game.options[pref.name])}
            {@html oneLineMarked(
              pref.label + ": " + pref.items.find((x) => x.name === $game.game.options[pref.name])?.label
            )}
          {/if}
        </Badge>
      {/each}
    </div>
  {/if}
  <div class="my-3" />
</Portal>

<style lang="postcss" global>
  .your-turn {
    color: #25ee25;
  }

  .vertical-textarea {
    resize: vertical;
  }

  #sidebar {
    .player-row.active .player-name {
      color: #25ee25 !important;
    }
    .player-name {
      &.dropped {
        text-decoration: line-through;
      }
    }
    .player-avatar {
      width: 1.8em;
      height: 1.8em;

      &.active {
        box-shadow: 0 0 3px #25ee25;
      }

      .vp {
        z-index: 100;
        width: 18px;
        border-radius: 5px;
        font-size: 0.6em;
      }
    }
  }
</style>

// webapp-vue/src/components/GameSidebar.vue
<template>
  <div>
    <portal to="sidebar">
      <h3 class="mt-75">Players</h3>
      <div
        v-for="player in game.players"
        :key="player._id"
        :class="['mb-1 d-flex align-items-center player-row', { active: isCurrentPlayer(player._id) }]"
      >
        <div
          :style="`background-image: url('${
            player.faction ? `/images/factions/icons/${player.faction}.svg` : `/api/user/${player._id}/avatar`
          }')`"
          :title="player.faction || 'unknown'"
          :class="['player-avatar', 'mr-2', { current: user && player._id === user }]"
        >
          <span :class="['vp', status(player._id)]">{{ player.score }}</span>
        </div>
        <router-link :to="`/user/${player.name}`" :class="['player-name', { dropped: player.dropped }]">{{
          player.name
        }}</router-link>
        <sup class="ml-1">
          <template v-if="player.elo">
            {{ player.elo.initial }} {{ player.elo.delta | sign }} {{ Math.abs(player.elo.delta) }} elo
          </template>
          <template v-else> {{ playerElo(player._id) }} elo </template>
        </sup>
        <span v-if="game.status === 'active'" class="ml-1"> - {{ remainingTime(player) | shortDuration }}</span>
      </div>
      <div class="mt-75">
        <b-icon icon="clock-history" class="mr-1" />
        {{
          alwaysActive
            ? "24h"
            : `${timerTime(game.options.timing.timer.start)}-${timerTime(game.options.timing.timer.end)}`
        }}
        / {{ game.options.timing.timePerGame | duration }} + {{ game.options.timing.timePerMove | duration }}
      </div>
      <div class="mt-75" v-if="game.status === 'ended'">
        <b> Game ended! </b>
      </div>
      <div v-if="user && isCurrentPlayer(user._id)" class="mt-75">
        <b class="your-turn">Your turn!</b>
      </div>
      <div v-if="playerUser && game.status !== 'ended'" class="mt-75">
        <b-btn
          variant="warning"
          size="sm"
          :disabled="playerUser.dropped || playerUser.voteCancel || playerUser.quit"
          @click="voteCancel"
          >Vote to cancel</b-btn
        >
        <b-btn
          size="sm"
          class="ml-2"
          v-if="game.players.some((pl) => !!pl.dropped)"
          :disabled="playerUser.dropped || playerUser.quit"
          @click="quit"
          >Quit</b-btn
        >
      </div>
      <div class="mt-75" v-if="gameInfo && gameInfo.preferences.length > 0">
        <h3>Preferences</h3>
        <div v-for="pref in preferenceItems" :key="pref.name">
          <b-checkbox v-model="preferences[pref.name]" @change="postPreferences">
            {{ pref.label }}
          </b-checkbox>
        </div>
      </div>

      <div class="mt-75">
        <div class="d-flex align-items-baseline">
          <h3 class="mb-0">Notes</h3>
          <div class="ml-2" style="font-size: smaller">
            (<a href="#" style="font-weight: unset !important" @click.prevent="showNotes = !showNotes">{{
              showNotes ? "hide" : "show"
            }}</a
            >)
          </div>
        </div>
        <b-form-textarea
          class="mt-2"
          style="resize: vertical"
          v-if="showNotes"
          v-model="notes"
          @change="updateNotesDebounce(game._id)"
          rows="3"
          max-rows="8"
          placeholder="You can make plans here..."
          :disabled="!user || !hasReceivedNotes"
        >
        </b-form-textarea>
      </div>

      <div class="mt-75" v-if="gameInfo && gameInfo.expansions.length > 0 && game.game.expansions.length > 0">
        <h3>Expansions</h3>
        <div v-for="expansion in game.game.expansions" :key="expansion">
          <b-badge variant="info" class="mr-1">{{
            gameInfo.expansions.find((xp) => xp.name === expansion).label
          }}</b-badge>
        </div>
      </div>

      <div class="mt-75 thin-scrollbar" v-if="log.length > 0">
        <div class="d-flex align-items-baseline">
          <h3 class="mb-0">Log</h3>
          <div class="ml-2" style="font-size: smaller">
            (<a href="#" style="font-weight: unset !important" @click.prevent="showLog = !showLog">{{
              showLog ? "hide" : "show"
            }}</a
            >)
          </div>
        </div>
        <div class="log mt-2" ref="log" v-if="showLog">
          <div v-for="(item, i) in [...log].reverse()" :key="i" v-html="logToHtml(item)"></div>
        </div>
      </div>

      <div v-if="gameInfo && gameInfo.viewer.replayable" class="mt-75">
        <b-btn variant="info" size="sm" @click="startReplay" v-if="!replayData">Replay</b-btn>
        <div v-else class="d-flex align-items-center">
          <b-btn size="sm" class="mr-1" @click="replayTo(replayData.start)"><b-icon icon="skip-backward-fill" /></b-btn>
          <b-btn size="sm" class="mx-1" @click="replayTo(Math.max(replayData.start, replayData.current - 1))"
            ><b-icon icon="skip-start-fill"
          /></b-btn>
          <span
            class="mx-1 text-center"
            style="text-overflow: ellipsis; overflow: hidden; white-space: nowrap; flex-grow: 1"
          >
            {{ replayData.current }} / {{ replayData.end }}
          </span>
          <b-btn size="sm" class="mx-1" @click="replayTo(Math.min(replayData.end, replayData.current + 1))"
            ><b-icon icon="skip-end-fill"
          /></b-btn>
          <b-btn size="sm" class="mx-1" @click="replayTo(replayData.end)"><b-icon icon="skip-forward-fill" /></b-btn>
          <b-btn size="sm" class="ml-1" @click="endReplay"><b-icon icon="stop-fill" variant="danger" /></b-btn>
        </div>
      </div>

      <div
        class="mt-75"
        v-if="
          gameInfo &&
          gameInfo.options.length > 0 &&
          game.game.options &&
          gameInfo.options.some((x) => !!game.game.options[x.name])
        "
      >
        <h3>Setup options</h3>
        <div v-for="pref in gameInfo.options.filter((x) => !!game.game.options[x.name])" :key="pref.name">
          <b-badge variant="secondary" class="mr-1">
            <span v-html="oneLineMarked(pref.label)" v-if="pref.type === 'checkbox'" />
            <span
              v-else-if="
                pref.type === 'select' && pref.items && pref.items.some((x) => x.name === game.game.options[pref.name])
              "
              v-html="
                oneLineMarked(pref.label + ': ' + pref.items.find((x) => x.name === game.game.options[pref.name]).label)
              "
            />
          </b-badge>
        </div>
      </div>
    </portal>
  </div>
</template>
<script lang="ts">
import { Vue, Component, Prop, Watch } from "vue-property-decorator";
import type { Game } from "../types";
import debounce from "lodash/debounce";
import { isEqual, keyBy } from "lodash";
import { timerTime, oneLineMarked, handleError } from "../utils";
import DOMPurify from "dompurify";
import { PlayerInfo } from "@lib/game";

@Component({
  created() {
    console.log("game sidebar created");
    this.loadNotes();
    this.loadPreferences();

    const interval = setInterval(() => {
      if (!document.hidden) {
        this.secondsCounter += 1;
      }
    }, 1000);
    this.$once("hook:beforeDestroy", () => clearInterval(interval));

    this.showLog = !!localStorage.getItem("show-log");
    this.showNotes = localStorage.getItem("show-notes") !== "false";
  },
})
export default class GameSidebar extends Vue {
  @Prop()
  game!: Game;

  @Prop()
  players!: Array<{ id: string; elo: number; name: string }>;

  @Prop({ default: () => [] })
  log: string[];

  @Prop({ default: null })
  replayData: { stard: number; end: number; current: number } | null;

  showLog = false;
  showNotes = false;

  notes = "";

  get preferenceItems() {
    let data = this.gameInfo?.preferences;

    if (data && this.gameInfo?.viewer?.alternate?.url) {
      data = [{ name: "alternateUI", label: "Use alternate UI", type: "checkbox", items: null }, ...data];
    }

    return data;
  }

  get preferences() {
    return this.$gameSettings.settings(this.game?.game.name)?.preferences ?? {};
  }

  get user() {
    return this.$store.state.user;
  }

  get playerUser() {
    return this.game.players.find((pl) => pl._id === this.user?._id);
  }

  get activePlayers() {
    return this.game.players.filter((pl) => this.game.currentPlayers?.some((pl2) => pl._id === pl2._id));
  }

  status(playerId: string) {
    return this.$store.state.playerStatus.find((pl) => pl._id === playerId)?.status;
  }

  playerElo(playerId: string) {
    return this.players.find((pl) => pl.id === playerId)?.elo ?? 0;
  }

  get gameInfo() {
    if (!this.game) {
      return null;
    }
    return this.$gameInfo.info(this.game.game.name, this.game.game.version);
  }

  get alwaysActive() {
    return this.game.options.timing.timer?.start === this.game.options.timing.timer?.end;
  }

  timerTime = timerTime;

  logToHtml(log: string) {
    return DOMPurify.sanitize(oneLineMarked(log));
  }

  get currentPlayersById() {
    console.log("current players by id");
    return keyBy(this.game?.currentPlayers ?? [], "_id");
  }

  isCurrentPlayer(id: string) {
    return this.game.status !== "ended" && !!this.currentPlayersById[id];
  }

  remainingTime(player: PlayerInfo) {
    const currentPlayer = this.currentPlayersById[player._id];
    if (currentPlayer) {
      // Trick to update every second
      return Math.floor((new Date(currentPlayer.deadline).getTime() - Date.now() + (this.secondsCounter % 1)) / 1000);
    }
    return Math.max(player.remainingTime, 0);
  }

  updateNotesDebounce = debounce(this.updateNotes.bind(this), 800, { leading: false, trailing: true });

  private async updateNotes(gameId: string) {
    if (gameId !== this.game._id) {
      return;
    }
    await this.$axios.post(`/game/${this.game._id}/notes`, { notes: this.notes });
  }

  async postPreferences() {
    if (!this.$store.state.user) {
      return;
    }
    await this.$axios.post(
      `/account/games/${this.game.game.name}/preferences/${this.game.game.version}`,
      this.preferences
    );
  }

  async voteCancel() {
    const doIt = await this.$bvModal.msgBoxConfirm(
      "This vote cannot be taken back. If all active players vote to cancel, the game will be cancelled."
    );

    if (doIt) {
      await this.$axios.post(`/game/${this.game._id}/cancel`).catch(handleError);
    }
  }

  async quit() {
    await this.$axios.post(`/game/${this.game._id}/quit`).catch(handleError);
  }

  startReplay() {
    this.$emit("replay:start");
  }

  replayTo(dest: number) {
    this.$emit("replay:to", dest);
  }

  endReplay() {
    this.$emit("replay:end");
  }

  @Watch("game")
  @Watch("user")
  async loadNotes() {
    this.hasReceivedNotes = false;
    if (this.game && this.user) {
      this.receivedNotes = await this.$axios.get(`/game/${this.game._id}/notes`).then((r) => r.data);
      this.notes = this.receivedNotes;
      this.hasReceivedNotes = true;
    }
  }

  @Watch("game.game.name")
  @Watch("user._id")
  async loadPreferences() {
    this.$gameSettings.loadSettings(this.game?.game.name);
  }

  @Watch("notes")
  saveNotesIfNeeded() {
    if (this.notes !== this.receivedNotes) {
      delete this.receivedNotes;
      this.updateNotesDebounce(this.game._id);
    }
  }

  @Watch("showLog")
  onShowLogChanged() {
    localStorage.setItem("show-log", this.showLog ? "true" : "");
  }

  @Watch("showNotes")
  onShowNotesChanged() {
    localStorage.setItem("show-notes", this.showNotes ? "true" : "false");
  }

  hasReceivedNotes = false;
  receivedNotes = "";
  secondsCounter = 0;
  oneLineMarked = oneLineMarked;
}
</script>
<style lang="scss">
.your-turn {
  color: #25ee25;
}

.sidebar {
  .player-row.active .player-name {
    color: #25ee25 !important;
  }
  .player-name {
    &.dropped {
      text-decoration: line-through;
    }
  }
  .player-avatar {
    width: 1.8em;
    height: 1.8em;

    &.active {
      box-shadow: 0 0 3px #25ee25;
    }

    .vp {
      z-index: 100;
      width: 18px;
      border-radius: 5px;
      font-size: 0.6em;

      &.online {
        background-color: #25ee25;
      }

      &.away {
        background-color: orange;
      }
    }
  }

  .log {
    height: 300px;
    overflow-y: scroll;

    margin-top: 4px;
    padding-left: 12px;
    border: 1px solid rgb(51, 51, 51);
    border-radius: 8px;
    padding-right: 12px;
  }
}
</style>
