// webapp-svelte/src/components/Layout/GameListSidebar.svelte
<script lang="ts">
import { latestBoardgames, loadBoardgames } from "@/api";
import { ListGroup, ListGroupItem } from "@/modules/cdk";
import { route, routePath } from "@/modules/router";
import { boardgames } from "@/store";
import { handleError } from "@/utils";
import type { GameInfo } from "@lib/gameinfo";

loadBoardgames().catch(handleError)

let games: GameInfo[]
$: games = latestBoardgames() as GameInfo[], [$boardgames]

function gameRoute(gameId: string) {
  if (gameId === $route!.params.boardgameId) {
    if ($route!.name === "boardgame") {
      return "/refresh-games";
    } else {
      return routePath({
        name: "boardgame",
        params: { boardgameId: gameId },
      });
    }
  }

  if (!$route!.params.boardgameId) {
    return routePath({
      name: "boardgame",
      params: { boardgameId: gameId },
    });
  }

  return routePath({
    name: $route!.name,
    hash: $route!.hash,
    params: { ...$route!.params, boardgameId: gameId },
  });
}
</script>

<ListGroup flush class="d-none d-lg-block ml-n3" style="width: 250px">
  {#each games as game}
    <ListGroupItem
      href={gameRoute(game._id.game)}
      action
      class={$route.params.boardgameId === game._id.game ? "active" : ""}
    >
      <span style="font-weight: 600">{game.label}</span>
    </ListGroupItem>
  {/each}
</ListGroup>

// webapp-vue/src/components/GameListSidebar.vue
<template>
  <b-list-group flush class="d-none d-lg-block ml-n3" style="width: 250px">
    <b-list-group-item
      v-for="game in games"
      :to="gameRoute(game._id.game)"
      :class="{ active: $route.params.boardgameId === game._id.game }"
      :key="game._id.game"
    >
      <span style="font-weight: 600">{{ game.label }}</span>
    </b-list-group-item>
  </b-list-group>
</template>
<script lang="ts">
import { Vue, Component, Prop, Watch } from "vue-property-decorator";

@Component
export default class GameListSidebar extends Vue {
  get games() {
    return this.$gameInfo.latest;
  }

  gameRoute(gameId: string) {
    if (gameId === this.$route.params.boardgameId) {
      if (this.$route.name === "boardgame") {
        return "/refresh-games";
      } else {
        return {
          name: "boardgame",
          params: { boardgameId: gameId },
        };
      }
    }

    if (!this.$route.params.boardgameId) {
      return {
        name: "boardgame",
        params: { boardgameId: gameId },
      };
    }

    return {
      name: this.$route.name,
      hash: this.$route.hash,
      params: { ...this.$route.params, boardgameId: gameId },
    };
  }
}
</script>
<style lang="scss"></style>
