// webapp-svelte/src/components/User/UserGames.svelte
<script lang="ts">
import { Card, Col, Row } from "@/modules/cdk";
import GameList from "../Game/components/GameList.svelte";

export let userId: string;
</script>

<Card class="mt-4 border-info" header="Games">
  <Row>
    <Col lg={6} class="mb-3">
      <GameList gameStatus="active" perPage={5} {userId} title="Active games" />
    </Col>
    <Col lg={6}>
      <GameList gameStatus="ended" perPage={5} {userId} title="Finished games" />
    </Col>
  </Row>
</Card>

// webapp-vue/src/components/UserGames.vue
<template>
  <b-card v-if="userId" border-variant="info" class="mt-4" header="Games">
    <b-row>
      <b-col lg="6" class="mb-3">
        <GameList gameStatus="active" :perPage="5" :userId="userId" title="Active games" />
      </b-col>
      <b-col>
        <GameList gameStatus="closed" :perPage="5" :userId="userId" title="Finished games" />
      </b-col>
    </b-row>
  </b-card>
</template>

<script lang="ts">
import { Vue, Component, Prop, Watch } from "vue-property-decorator";
import { handleError } from "@/utils";
import { IGame } from "@lib/game";
import { IUser } from "@lib/user";
import GameList from "./GameList.vue";

@Component({
  components: {
    GameList,
  },
})
export default class UserGames extends Vue {
  @Prop({ default: null })
  userId: string;

  get loggedUser(): IUser {
    return this.$store.state.user;
  }
}
</script>
