// packages/web/admin-app/src/pages/login.vue
<script setup lang="ts">
import { reactive } from "vue-demi";
import { post } from "~/api/rest";
import { handleError } from "~/utils";

const form = reactive({
  email: "",
  password: "",
});

async function login() {
  try {
    const data = await post("/account/login", { email: form.email, password: form.password });
    // this.$store.dispatch("updateAuth", data);
  }
  catch (err) {
    handleError(err);
  }
}
</script>

<template>
  <form @submit.prevent="login">
    <v-text-field v-model="form.email" label="Email" required type="email" />
    <v-text-field v-model="form.password" label="Password" required type="password" />
    <v-btn color="primary" type="submit"> Log in </v-btn>
  </form>
</template>

// packages/web/webapp-svelte/src/pages/auth/Login.svelte
<script lang="ts">
  import { login } from "@/api";
  import { Button, FormGroup, Label } from "@/modules/cdk";
  import { handleError } from "@/utils";
  
  let email = "";
  let password = "";

  function handleLogin() {
    login(email, password).catch(handleError);
  }
</script>

<form on:submit|preventDefault={handleLogin}>
  <FormGroup>
    <Label for="email">Email</Label>
    <input
      bind:value={email}
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Email address"
      required
    />
  </FormGroup>
  <FormGroup>
    <Label for="password">Password</Label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Password"
      bind:value={password}
      required
    />
    <div class="text-right mt-1">
      <a href="/forgotten-password"><small>Forgotten password ?</small></a>
    </div>
  </FormGroup>
  <Button type="submit" color="primary" class="pull-right">Login</Button>
</form>

<hr />

<p>Need an account ? <a href="/signup">Register</a></p>
