// admin-app/src/views/Login.vue
<template>
  <form @submit.prevent="login">
    <v-text-field label="Email" required v-model="form.email" type="email" />
    <v-text-field label="Password" required v-model="form.password" type="password" />
    <v-btn color="primary" type="submit">Log in</v-btn>
  </form>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";
import { handleError } from "@/utils";

@Component
export default class Login extends Vue {
  form = {
    email: "",
    password: "",
  };

  login() {
    this.$axios.post("/account/login", { email: this.form.email, password: this.form.password }).then(
      ({ data }) => {
        this.$store.dispatch("updateAuth", data);
      },
      (err) => handleError(err)
    );
  }
}
</script>

// packages/web/webapp-svelte/src/pages/auth/Login.svelte
<script lang="ts">
  import { login } from "@/api";
  import { Button, FormGroup, Label } from "@/modules/cdk";
  import { handleError } from "@/utils";
  
  let email = "";
  let password = "";

  function handleLogin() {
    login(email, password).catch(handleError);
  }
</script>

<form on:submit|preventDefault={handleLogin}>
  <FormGroup>
    <Label for="email">Email</Label>
    <input
      bind:value={email}
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Email address"
      required
    />
  </FormGroup>
  <FormGroup>
    <Label for="password">Password</Label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Password"
      bind:value={password}
      required
    />
    <div class="text-right mt-1">
      <a href="/forgotten-password"><small>Forgotten password ?</small></a>
    </div>
  </FormGroup>
  <Button type="submit" color="primary" class="pull-right">Login</Button>
</form>

<hr />

<p>Need an account ? <a href="/signup">Register</a></p>
