// webapp-vue/src/views/Account.vue
<template>
  <div class="container account">
    <b-row>
      <b-col
        ><h1>{{ user.account.username }}</h1></b-col
      >
      <b-col class="text-right"
        ><b-button variant="primary" :to="{ name: 'user', params: { username: user.account.username } }"
          >Profile</b-button
        ></b-col
      >
    </b-row>

    <b-card-group deck class="game-choice mt-4">
      <UserGameSettings :game="game" v-for="game in $gameInfo.latest" :key="game._id.game" />
    </b-card-group>

    <b-card border-variant="info" class="mt-4" header="User Settings">
      <p v-if="user.account.username">
        Username: <strong>{{ user.account.username }}</strong>
      </p>
      <div class="form-group">
        <label for="email">Email</label>
        <b-input-group>
          <b-form-input
            type="email"
            placeholder="Email address"
            v-model.trim="email"
            @keyup.prevent.stop.enter.native="saveEmail"
            :disabled="!editingEmail"
          />
          <template #append>
            <b-button variant="outline-secondary" v-if="!editingEmail" @click="editingEmail = true">Edit</b-button>
            <b-button variant="outline-success" v-if="editingEmail" @click="saveEmail">Save</b-button>
          </template>
        </b-input-group>
        <small v-if="user.security.confirmed">Your email is confirmed.</small>
        <small v-else>Your email is not confirmed.</small>
      </div>
      <p>
        Connect with
        <b-btn
          variant="google"
          class="mx-1"
          href="/api/account/auth/google"
          :disabled="!!(user.account.social && user.account.social.google)"
          >Google</b-btn
        >
        <b-btn
          variant="discord"
          class="mx-1"
          href="/api/account/auth/discord"
          :disabled="!!(user.account.social && user.account.social.discord)"
          >Discord</b-btn
        >
        <b-btn
          variant="facebook"
          class="mx-1"
          href="/api/account/auth/facebook"
          :disabled="!!(user.account.social && user.account.social.facebook)"
          >Facebook</b-btn
        >
      </p>
      <b-checkbox v-if="!user.account.termsAndConditions" class="mb-3" v-model="tc" @change="acceptTC"
        >I agree to the <router-link to="/page/terms-and-conditions">Terms and Conditions</router-link></b-checkbox
      >
      <p v-else>
        I accepted the <router-link to="/page/terms-and-conditions">Terms and Conditions</router-link> on
        {{ user.account.termsAndConditions | niceDate }}.
      </p>
      <hr />
      <b-checkbox v-model="newsletter" @change="updateAccountDebounce">
        Get newsletter, up to six emails per year.</b-checkbox
      >
      <div class="form-row align-items-center">
        <div class="col-auto">
          <b-checkbox v-model="gameNotification" @change="updateAccountDebounce">
            Receive an email when it's your turn after a delay of
          </b-checkbox>
        </div>
        <div class="col-auto">
          <select
            class="form-control form-control-sm"
            v-model="gameNotificationDelay"
            @change="
              gameNotification = true;
              updateAccountDebounce();
            "
          >
            <option
              v-for="val of [60, 5 * 60, 10 * 60, 30 * 60, 2 * 3600, 6 * 3600, 12 * 3600]"
              :value="val"
              :key="val"
            >
              {{ val | duration }}
            </option>
          </select>
        </div>
      </div>
    </b-card>
    <b-card border-variant="info" class="mt-4" header="Game Settings">
      <b-checkbox v-model="soundNotification" @change="updateAccountDebounce"
        >Play a sound when it's your turn in one of your games</b-checkbox
      >
      <b-checkbox v-model="notifications">Notification on this device when it's your turn</b-checkbox>
    </b-card>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue, Watch } from "vue-property-decorator";
import { IUser } from "@lib/user";
import { handleError } from "@/utils";
import debounce from "lodash/debounce";
import UserGames from "../components/UserGames.vue";
import UserGameSettings from "../components/UserGameSettings.vue";
import UserPublicInfo from "../components/UserPublicInfo.vue";
import UserElo from "../components/UserElo.vue";
import { IGame } from "@lib/game";

@Component<Account>({
  components: {
    UserGames,
    UserGameSettings,
    UserPublicInfo,
    UserElo,
  },
  created() {
    this.$gameInfo.loadAll();
    this.notifications = !!localStorage.getItem("notifications");
  },
})
export default class Account extends Vue {
  email: string = "";
  editingEmail = false;
  newsletter: boolean = false;
  soundNotification: boolean = false;
  notifications = false;
  gameNotification: boolean = false;
  gameNotificationDelay: number = 30 * 60;
  tc = false;

  constructor() {
    super();

    this.email = this.user.account.email;
    this.soundNotification = !!this.user.settings?.game?.soundNotification;
    this.newsletter = !!this.user.settings?.mailing?.newsletter;
    this.gameNotification = !!this.user.settings?.mailing?.game?.activated;
    this.gameNotificationDelay = this.user.settings?.mailing?.game?.delay ?? 30 * 60;
    this.updateAccount.bind(this);
  }

  get user(): IUser {
    return this.$store.state.user;
  }

  async acceptTC() {
    const accepted = await this.$bvModal.msgBoxConfirm(
      "The terms and conditions will be marked as accepted at today's date."
    );

    if (!accepted) {
      this.tc = false;
      return;
    }

    try {
      const user = await this.$axios.post("/account/terms-and-conditions").then((r) => r.data);
      this.$store.commit("updateUser", user);
    } catch (err) {
      handleError(err);
    }
  }

  updateAccount() {
    this.$axios
      .post("/account", {
        settings: {
          mailing: {
            newsletter: this.newsletter,
            game: {
              activated: this.gameNotification,
              delay: this.gameNotificationDelay,
            },
          },
          game: {
            soundNotification: this.soundNotification,
          },
        },
      })
      .then(
        (r) => this.$store.commit("updateUser", r.data),
        (err) => handleError(err)
      );
  }

  async saveEmail() {
    try {
      const data = await this.$axios.post("/account/email", { email: this.email }).then((response) => response.data);
      this.$store.commit("updateUser", data);
    } catch (err) {
      handleError(err);
    }
  }

  @Watch("notifications")
  notificationsChanged() {
    if (this.notifications) {
      if (Notification.permission !== "granted") {
        Notification.requestPermission();
      }
    }

    if (!!localStorage.getItem("notifications") !== this.notifications) {
      localStorage.setItem("notifications", this.notifications ? "1" : "");
    }
  }

  updateAccountDebounce = debounce(this.updateAccount, 800, { leading: false });
}
</script>

// packages/web/webapp-svelte/src/pages/Account.svelte
<script lang="ts">
import { handleError, confirm, niceDate, duration, createWatcher } from "@/utils";
import { UserGameSettings } from "@/components";
import { Card, CardDeck , InputGroupAddon, Button, Col, Container, FormGroup, Input, InputGroup, Row, Label, Checkbox } from "@/modules/cdk";
import { boardgames, user } from "@/store";
import { routePath } from "@/modules/router";
import { upperFirst, debounce } from "lodash";
import { latestBoardgames, loadBoardgames, post } from "@/api";
import type { GameInfo } from "@lib/gameinfo";

loadBoardgames().catch(handleError)

let games: GameInfo[]
$: games = latestBoardgames() as GameInfo[], [$boardgames]

let email = $user!.account.email;
let editingEmail = false;
let notifications = !!localStorage.getItem("notifications");
let newsletter = $user!.settings?.mailing?.newsletter;
let soundNotification = $user!.settings?.game?.soundNotification;
let gameNotification = $user!.settings?.mailing?.game?.activated;
let gameNotificationDelay = $user!.settings?.mailing?.game?.delay ?? 30 * 60;
let tc = false;

async function acceptTC() {
  const accepted = await confirm(
    "The terms and conditions will be marked as accepted at today's date."
  );

  if (!accepted) {
    tc = false;
    return;
  }

  try {
    user.set(await post("/account/terms-and-conditions"));
  } catch (err) {
    handleError(err);
  }
}

const updateAccount = debounce(() => {
  post("/account", {
    settings: {
      mailing: {
        newsletter,
        game: {
          activated: gameNotification,
          delay: gameNotificationDelay,
        },
      },
      game: {
        soundNotification,
      },
    },
  })
  .then(
    (r) => user.set(r),
    handleError
  );
}, 800, {leading: false});

async function saveEmail() {
  try {
    user.set(await post("/account/email", { email }));
  } catch (err) {
    handleError(err);
  }
}

const onNotificationsChanged = createWatcher(() => {
  if (notifications) {
    if (Notification.permission !== "granted") {
      Notification.requestPermission();
    }
  }

  if (!!localStorage.getItem("notifications") !== notifications) {
    localStorage.setItem("notifications", notifications ? "1" : "");
  }
})

$: onNotificationsChanged(notifications)
</script>

{#if $user}
  <Container>
    <Row>
      <Col>
        <h1>{$user.account.username}</h1>
      </Col>
      <Col class="text-right">
        <a
          class="btn btn-primary"
          href={routePath({ name: "user", params: { username: $user.account.username } })}
          role="button">Profile</a
        >
      </Col>
    </Row>

    <CardDeck class="game-choice mt-4">
      {#each games as game}
        <UserGameSettings {game} />
      {/each}
    </CardDeck>

    <Card class="mt-4 border-info" header="User Settings">
      <p>
        Username: <strong>{$user.account.username}</strong>
      </p>
      <FormGroup>
        <label for="email">Email</label>
        <InputGroup>
          <Input
            type="email"
            placeholder="Email address"
            bind:value={email}
            on:keyup={(e) => {
              if (e.keyCode === 13) {
                e.preventDefault();
                e.stopPropagation();
                saveEmail();
              }
            }}
            disabled={!editingEmail}
          />

          <InputGroupAddon addonType="append">
            {#if !editingEmail}
              <Button outline color="secondary" on:click={() => (editingEmail = true)}>Edit</Button>
            {:else}
              <Button outline color="success" on:click={saveEmail}>Save</Button>
            {/if}
          </InputGroupAddon>
        </InputGroup>
        <small>{$user.security.confirmed ? "Your email is confirmed." : "Your email is not confirmed."}</small>
      </FormGroup>
      <p>
        Connect with

        {#each ["google", "discord", "facebook"] as social}
          <a
            class={`btn btn-secondary mx-1 ${social}`}
            class:disabled={!!($user.account.social && $user.account.social[social])}
            href={`/api/account/auth/${social}`}
            aria-disabled={!!($user.account.social && $user.account.social[social])}
            role="button"
            rel="external"
          >
            {upperFirst(social)}
          </a>
        {/each}
      </p>
      {#if !$user.account.termsAndConditions}
        <Checkbox bind:checked={tc} on:change={acceptTC} class="mb-3">
          I agree to the <a href="/page/terms-and-conditions">Terms and Conditions</a>
        </Checkbox>
      {:else}
        <p>
          I accepted the <a href="/page/terms-and-conditions">Terms and Conditions</a> on
          {niceDate($user.account.termsAndConditions)}.
        </p>
      {/if}
      <hr />
      <Checkbox bind:checked={newsletter} on:change={updateAccount}>Get newsletter, up to six emails per year.</Checkbox
      >
      <div class="form-row align-items-center">
        <div class="col-auto">
          <Checkbox bind:checked={gameNotification} on:change={updateAccount}>
            Receive an email when it's your turn after a delay of
          </Checkbox>
        </div>
        <div class="col-auto">
          <select
            class="form-control form-control-sm"
            bind:value={gameNotificationDelay}
            on:blur={() => {
              gameNotification = true;
              updateAccount();
            }}
          >
            {#each [60, 5 * 60, 10 * 60, 30 * 60, 2 * 3600, 6 * 3600, 12 * 3600] as seconds}
              <option value={seconds}>
                {duration(seconds)}
              </option>
            {/each}
          </select>
        </div>
      </div>
    </Card>
    <Card class="mt-4 border-info" header="Game Settings">
      <Checkbox bind:checked={soundNotification} on:change={updateAccount}>
        Play a sound when it's your turn in one of your games
      </Checkbox>
      <Checkbox bind:checked={notifications}>Notification on this device when it's your turn</Checkbox>
    </Card>
  </Container>
{/if}
