// webapp-vue/src/views/Rankings.vue
<template>
  <div class="container">
    <h1>Rankings</h1>
    <b-row>
      <b-col md="6">
        <BoardgameElo :boardgameId="boardgameId" />
      </b-col>

      <b-col md="6">
        <h3>Tournaments</h3>
        <p>No Tournament ranking available</p>
      </b-col>
    </b-row>
  </div>
</template>
<script lang="ts">
import { Vue, Component, Prop, Watch } from "vue-property-decorator";
import { handleError } from "@/utils";
import BoardgameElo from "../components/BoardgameElo.vue";

@Component({
  components: {
    BoardgameElo,
  },
})
export default class Rankings extends Vue {
  @Prop()
  boardgameId: string;
}
</script>

// packages/web/webapp-svelte/src/pages/Rankings.svelte
<script lang="ts">
  import { BoardgameElo } from "@/components";
  import { Col, Row } from "@/modules/cdk";
  
   export let boardgameId: string
</script>

<div class="container">
  <h1>Rankings</h1>
  <Row>
    <Col md={6}>
      <BoardgameElo {boardgameId} perPage={10} />
    </Col>
    <!--
    <b-col md="6">
      <h3>Tournaments</h3>
      <p>No Tournament ranking available</p>
    </b-col>
-->
  </Row>
</div>
