// packages/web/webapp-svelte/src/pages/GameSelection.svelte
<script lang="ts">
import { latestBoardgames, loadBoardgames } from "@/api";
import { loadAllGameSettings } from "@/api/gamesettings";
import { CardDeck, Card, CardText } from "@/modules/cdk";
import Loading from "@/modules/cdk/Loading.svelte";
import { navigate } from "@/modules/router";
import { gameSettings, user } from "@/store";
import { handleError, confirm, createWatcher } from "@/utils";
import type { GameInfo } from "@lib/gameinfo";
import type { SetOptional } from "type-fest";

import marked from "marked";

export let newGame = false;
export let title = "Game selection"

let info = latestBoardgames();
let loading = info.length === 0;

loadBoardgames().then(() => {
  loading = false;
  info = latestBoardgames()
}).catch(handleError)

loadAllGameSettings().catch(handleError)

const watcher = createWatcher(() => Promise.all([loadBoardgames(), loadAllGameSettings()]))

$: watcher($user) 

const onGameClick  = async (gameInfo: SetOptional<GameInfo, 'viewer'>) => {
  if (newGame) {
    if (gameInfo.meta.needOwnership && !$gameSettings[gameInfo._id.game]?.access?.ownership) {
      await confirm("You need to have game ownership to host a new game. You can set game ownership in your account settings.");
    } else {
      navigate(`/new-game/${gameInfo._id.game}`)
    }
    return;
  }

  navigate(`/boardgame/${gameInfo._id.game}`);
}
</script>

<div class="container">
  <h1 class="mb-4">{title}</h1>
  <Loading {loading}>
    <CardDeck class="game-choice">
      {#each info as game}
        <Card header={game.label} class="border-secondary text-center" on:click={() => onGameClick(game)}>
          <CardText class="text-left">
            {@html marked(game.description)}
          </CardText>
          <span
            slot="footer"
            class:text-info={$gameSettings[game._id.game]?.access?.ownership}
            class:text-secondary={!$gameSettings[game._id.game]?.access?.ownership}
          >
            {#if $gameSettings[game._id.game]?.access?.ownership}
              You own this game
            {:else}
              You do not own this game
            {/if}
          </span>
        </Card>
      {/each}
    </CardDeck>
  </Loading>
</div>

<style lang="postcss" global>
  .game-choice {
    .card {
      transition: border-color;
      transition-duration: 0.3s;
      transition-timing-function: ease;
    }

    .card:hover {
      border-color: var(--info) !important;

      cursor: pointer;
    }

    .card-header {
      transition: color;
      transition-duration: 0.3s;
      transition-timing-function: ease;
    }
    .card:hover .card-header {
      color: var(--info);
    }
  }
</style>

// webapp-vue/src/views/GameSelection.vue
<template>
  <div class="container">
    <h1 class="mb-4">{{ title }}</h1>
    <v-loading :loading="loading">
      <b-card-group deck class="game-choice">
        <b-card
          v-for="game in info"
          :key="game._id.game + game._id.version"
          @click="cardClick(game._id.game)"
          border-variant="secondary"
          :header="game.label"
          align="center"
        >
          <b-card-text v-html="marked(game.description)" align="left"></b-card-text>
          <template #footer>
            <span
              v-if="$gameSettings.allSettings.some((x) => x.game === game._id.game && x.access.ownership)"
              class="text-info"
              >You own this game</span
            >
            <span v-else class="text-secondary">You do not own this game</span>
          </template>
        </b-card>
      </b-card-group>
    </v-loading>
  </div>
</template>
<script lang="ts">
import { Vue, Component, Prop, Watch } from "vue-property-decorator";
import { handleError } from "@/utils";
import marked from "marked";
import { GamePreferences } from "@lib/gamepreferences";

@Component
export default class GameSelection extends Vue {
  @Prop({ default: false, type: Boolean })
  newGame: boolean;

  @Prop({ default: "Game selection" })
  title: string;

  get loading() {
    return this.info.length === 0;
  }

  get info() {
    return this.$gameInfo.latest;
  }

  marked = marked;

  cardClick(game: string) {
    if (this.newGame) {
      if (
        this.$gameInfo.info(game, "latest").meta.needOwnership &&
        !this.$gameSettings.allSettings.some((x) => x.game === game && x.access.ownership)
      ) {
        this.$bvModal.msgBoxOk(
          "You need to have game ownership to host a new game. You can set game ownership in your account settings.",
          { title: "Game ownership needed" }
        );
      } else {
        this.$router.push(`/new-game/${game}`);
      }
      return;
    }

    this.$router.push(`/boardgame/${game}`);
  }

  @Watch("$store.state.user", { immediate: true })
  onUserUpdated() {
    this.$gameSettings.loadAll();
    this.$gameInfo.loadAll();
  }
}
</script>
<style lang="scss" scoped>
@import "../stylesheets/variables.scss";

.game-choice {
  .card {
    transition: border-color;
    transition-duration: 0.3s;
    transition-timing-function: ease;
  }

  .card:hover {
    border-color: $info !important;

    cursor: pointer;
  }

  .card-header {
    transition: color;
    transition-duration: 0.3s;
    transition-timing-function: ease;
  }
  .card:hover .card-header {
    color: $info;
  }
}
</style>
