// webapp-svelte/src/pages/User.svelte
<script lang="ts">
  import { handleError } from "@/utils";
  import type { IUser } from "@lib/user";
  import { UserGames, UserPublicInfo, UserElo} from "@/components";
  import { get } from "@/api";
  import { Row, Col, Container, Card, Loading } from "@/modules/cdk";
  import { user as ownUser } from "@/store"

  export let username: string;
  let user: IUser;

  const onUserNameChanged = () => get(`/user/infoByName/${encodeURIComponent(username)}`).then(r => user = r).catch(handleError)  
  $: onUserNameChanged(), [username]
</script>

<svelte:head>
  <title>{username} - Boardgamers 🌌</title>
</svelte:head>

<Container>
  <Row>
    <Col>
      <h1>{username}</h1>
    </Col>
    <Col class="text-right">
      {#if user && $ownUser?._id === user._id}
        <a class="btn btn-primary" href="/account" role="button">Settings</a>
      {/if}
    </Col>
  </Row>
  <Loading loading={!user}>
    <UserPublicInfo class="mt-4" {user} />
    <UserGames userId={user._id} />

    <Card class="border-info mt-4" header="Statistics">
      <Row>
        <Col lg={6} class="mb-3">
          <UserElo userId={user._id} />
        </Col>
        <Col>
          <h3 class="card-title">Tournaments</h3>
          <p>No Tournament info available</p>
        </Col>
      </Row>
    </Card>
  </Loading>
</Container>

// webapp-vue/src/views/User.vue
<template>
  <div class="container account">
    <b-row>
      <b-col
        ><h1>{{ username }}</h1></b-col
      >
      <b-col class="text-right"
        ><b-button
          variant="primary"
          to="/account"
          v-if="$store.state.user && user && $store.state.user._id === user._id"
          >Settings</b-button
        ></b-col
      >
    </b-row>
    <v-loading :loading="loading">
      <UserPublicInfo class="mt-4" v-if="user" :user="user" />
      <UserGames v-if="user" :userId="user._id" />
      <b-card border-variant="info" class="mt-4" header="Statistics">
        <b-row>
          <b-col lg="6" class="mb-3">
            <UserElo v-if="user" :userId="user._id" />
          </b-col>
          <b-col>
            <h3 class="card-title">Tournaments</h3>
            <p>No Tournament info available</p>
          </b-col>
        </b-row>
      </b-card>
    </v-loading>
  </div>
</template>
<script lang="ts">
import { Vue, Component, Prop, Watch } from "vue-property-decorator";
import { handleError, dateFromObjectId } from "@/utils";
import { IUser } from "@lib/user";
import UserGames from "../components/UserGames.vue";
import UserPublicInfo from "../components/UserPublicInfo.vue";
import UserElo from "../components/UserElo.vue";

@Component({
  async created(this: User) {
    try {
      this.user = await this.$axios.get(`/user/infoByName/${encodeURIComponent(this.username)}`).then((r) => r.data);
    } catch (err) {
      handleError(err);
    } finally {
      this.loading = false;
    }
  },
  components: {
    UserGames,
    UserPublicInfo,
    UserElo,
  },
})
export default class User extends Vue {
  loading = true;

  user: IUser = null;

  @Prop()
  username: string;
}
</script>
