// webapp-svelte/src/App.svelte
<script lang="typescript">
	import {onMount} from 'svelte';
	import Appbar from './components/Appbar.svelte';
	import Footer from './components/Footer.svelte';
  import { get } from "@/api";
  import { RouterView } from './modules/router';
	
	let announcement: string = "";

	onMount(() => {
		get('/site/announcement').then(ann => announcement = ann)	
	});
</script>

<div id="app">
  <div id="app-layout">
    <div style="flex-grow: 1; display: flex; flex-direction: column">
      <Appbar class="mb-2" />
      <main class="container-fluid p-relative mb-auto">
        <RouterView />
      </main>
      <Footer />
    </div>
  </div>
</div>

<style lang="postcss">
  :global(html) {
    min-height: 100%;
    height: 100%;
  }

  :global(body) {
    margin: 0;
    font-family: Arial, Helvetica, sans-serif;
    min-height: 100%;
    height: 100%;
  }

  #app {
    height: 100%;
    display: flex;
    flex-direction: column;
  }

  #app-layout {
    height: 100%;
    display: flex;
    flex-direction: row;
  }
</style>

// packages/web/admin-app/src/App.vue
<template>
  <v-app>
    <div id="app-navigation">
      <NavBar />
      <NavigationDrawer v-if="$route.meta && $route.meta.loggedIn" />
    </div>
    <v-main>
      <v-container class="main-content px-5 pt-5" fluid>
        <router-view />
      </v-container>
    </v-main>
    <Toaster />
  </v-app>
</template>

<script lang="ts">
import NavBar from "./components/NavBar.vue";
import NavigationDrawer from "./components/NavigationDrawer.vue";
import Toaster from "./components/Toaster.vue";

export default {
  name: "app",
  components: {
    NavBar,
    NavigationDrawer,
    Toaster,
  },
};
</script>

<style lang="scss">
@import "./style/main.scss";

#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
}

body {
  margin: 0;
}

html,
body,
#app {
  height: 100%;
}
</style>
