// webapp-vue/src/views/ForgottenPassword.vue
<template>
  <div class="goldfish container">
    <h1>Forgotten password</h1>

    <form method="post" accept-charset="UTF-8" role="form" class="clearfix" @submit.prevent="submit">
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Email address"
          v-model="email"
          required
        />
      </div>
      <button type="submit" class="btn btn-primary pull-right mt-3">Reset</button>
    </form>

    <hr />

    <p>Need an account? <router-link to="/signup">Register</router-link></p>
    <p>Or go back <router-link to="/">home</router-link>.</p>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";
import { handleError, handleInfo } from "@/utils";

@Component
export default class ForgottenPassword extends Vue {
  email = "";

  submit() {
    this.$axios.post("/account/forget", { email: this.email }).then(
      () => handleInfo("An email was sent to reset your password"),
      (err) => handleError(err)
    );
  }
}
</script>

// apps/web/src/routes/(app)/forgotten-password/+page.svelte
<script lang="ts">
  import { SEO } from "@/components";
  import { useLoggedOut } from "@/lib/auth-guards.svelte";
  import { post } from "@/lib/api";
  import { handleError, handleInfo } from "@/utils";

  useLoggedOut();
  let email = "";
  function handleSubmit() {
    post("/account/forget", { email }).then(() => handleInfo("An email was sent to reset your password"), handleError);
  }
</script>

<SEO title="Forgotten password" />
<div class="goldfish container">
  <h1>Forgotten password</h1>
  <form method="post" accept-charset="UTF-8" role="form" on:submit|preventDefault={handleSubmit}>
    <div class="form-group">
      <label for="email">Email</label>
      <input type="email" class="form-control" id="email" placeholder="Email address" bind:value={email} required />
    </div>
    <button type="submit" class="btn btn-primary pull-right mt-3">Reset</button>
  </form>
  <hr />
  <p>Need an account? <a href="/signup">Register</a></p>
  <p>Or go back <a href="/">home</a>.</p>
</div>
